### ISSUE TITLE
Reverse Geocoding bad response

### ISSUE THREAD

**Issue by ourmanflint** [Dimolll/google_geocoding_api#2]
Hi

I'm trying to use the supplied code to reverse geocode from a latlng String but only get a bad response error 400

`  _Future<void> getLocation() async {
    String googleApiKey = 'MY_API_KEY';
    bool isDebugMode = true;
    final api = GoogleGeocodingApi(googleApiKey, isLogged: isDebugMode);
    final reversedSearchResults = await api.reverse(
    '42.360083,-71.05888',
    language: 'en',
  );
  }
`

Debug console:
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: DioError [bad response]: The request returned an invalid status code of 400.
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:530:7)
#1      _RootZone.runBinary (dart:async/zone.dart:1665:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#5      Future._completeError (dart:async/future_impl.dart:575:5)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
#7      _Completer.completeError (dart:async/future_impl.dart:23:5)
#8      Future.any.onError (dart:async/future.dart:617:45)
#9      _RootZone.runBinary (dart:async/zone.dart:1665:54)
#10     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#12     Future._pro<…>

**Comment by ourmanflint** [comment]
error on my side
